### ISSUE TITLE
Detection issues under Chrome

### ISSUE THREAD

**Issue by peakwinter** [savoirfairelinux/ringme.js#18]
### Expected Behaviour

While using Chrome, the URI scheme detection should work properly from the first page load.

### Actual Behaviour

While using Chrome, the URI scheme does not appear to be detected until the user clears a "Ring presence is unknown" alert at least once.

### Steps to reproduce

* Click "Ring Me" after a first load.
* The download page redirect prompt appears.
* Click on Cancel.
* Ring opens successfully anyway.

### Notes

At the point where the alert window is opened, `this.isRingSchemeSupported()` returns `false`. But on subsequent attempts in the same browser session, it returns `true`. It's just this first run that either has a false detection or doesn't prevent the window from launching when the user clicks Cancel.

**Comment by ssirois** [comment]
Thanks to @samnegri and the #Hacktoberfest event, this issue is now fix.
