### ISSUE TITLE
On click please !

### ISSUE THREAD

**Issue by philippemouchel** [savoirfairelinux/ringme.js#2]
As now, when the button is printed, Ring is automatically open !!!
It should be open on click only !

**Comment by ssirois** [comment]
This is is indeed replicable.

It's a side-effect of the way the library is testing for `ring:` scheme support.

As much as I would personally prefer having a download link rendered when needed and a button rendered when the scheme is supported, until we find a better we, I shall provide a patch fixing this over the week.

**Comment by ssirois** [comment]
I shall work on this today. Thank you for your patience.
