### ISSUE TITLE
Fancy curly theme

### ISSUE THREAD

**Issue by ventilooo** [savoirfairelinux/ringme.js#24]
It would be cool to have a cute stylish webpage for the `gh-pages`. 
![shiba inu dog with sun glasses](https://media.giphy.com/media/l2JI304n1oBhOPYXu/giphy.gif)

**Comment by Sneakykicks** [comment]
Ok Sure

**Comment by flyingfisch** [comment]
Is this still up for grabs? If so, I'll take it.

**Comment by ventilooo** [comment]
Hi @flyingfisch ,
Thanks for your interest in our project !
You can grab this task  :tada:

**Comment by ssirois** [comment]
@flyingfisch, @ventilooo: The [_gh-pages_ branch](/savoirfairelinux/ringme.js/tree/gh-pages) has just been updated with latest version.

**Comment by ssirois** [comment]
Here we are with a [fancy new page](https://savoirfairelinux.github.io/ringme.js/), thanks to @flyingfisch for this contribution.

We shall _improve_ padding usage for smaller screen. Nothing big, just small tweaks. So small details that https://github.com/savoirfairelinux/ringme.js/pull/47 couldn't have been postponed for that.

Thanks again.

**Comment by flyingfisch** [comment]
Ah yes, good point. If you don't mind I may optimize it for mobile tomorrow if I have time.
