### ISSUE TITLE
Add Eslint to the project

### ISSUE THREAD

**Issue by ventilooo** [savoirfairelinux/ringme.js#30]
### Expected Behaviour
It would be great for maintainability and developers happiness to have lint
Since it's an `Javascript` a simple `.eslintrc` file should be enough !

[Documentation](https://eslint.org/docs/user-guide/configuring)

### Actual Behaviour

There is no lint rules.

**Comment by nabrahamson** [comment]
A pull request has been created for this issue [here](https://github.com/savoirfairelinux/ringme.js/pull/34)
