### ISSUE TITLE
Add EditorConfig file

### ISSUE THREAD

**Issue by ventilooo** [savoirfairelinux/ringme.js#31]
### Expected Behaviour

Since we all use various IDE or text editor and lint rules are comming with #30 
An editorconfig file should help all of us to comply to it :)

[Documentation](http://editorconfig.org/)

### Actual Behaviour

Tabs **vs** space ? 

![troll](https://media.giphy.com/media/XFUiHxWQYzvi/giphy.gif)

**Comment by phscherer** [comment]
Hi, I'm interested, is there any specific rule for executing this issue? :smiley:

**Comment by ventilooo** [comment]
Hi @phscherer,
Exept having 4 spaces instead of tabs ... 
@ssirois @peakwinter Any recommendation ?

**Comment by yongzhihuang** [comment]
Hi @ventilooo PR here: https://github.com/savoirfairelinux/ringme.js/pull/35

**Comment by ssirois** [comment]
4 spaces instead of tabs seems like _just enough software_ for now!

👍

**Comment by ssirois** [comment]
#35 has been merge to trunk.

Thank your @yongzhihuang
