### ISSUE TITLE
upgade library to ES6

### ISSUE THREAD

**Issue by combmag-zz** [savoirfairelinux/ringme.js#44]
Hi guys,

As a suggestion i was thinking to update the library using typescript so that we can use ES6+ features. What do you think? I can try to make a PR this week.

**Comment by ventilooo** [comment]
Hi @combmag,

This project aim to stay a little library. 
None of the maintainer know typescript well enough to pivot to that language.
You are free to create another project with a typescript version (with a link to the orginal project)

Hope my answer help you !

**Comment by combmag-zz** [comment]
ok closing issue then
