### ISSUE TITLE
Publish this project on npmjs.com

### ISSUE THREAD

**Issue by ssirois** [savoirfairelinux/ringme.js#50]
### Expected Behaviour

This project should be available on [npmjs.com under savoirfairelinux's organisation](https://www.npmjs.com/org/savoirfairelinux)

### Actual Behaviour

Nothing there.

**Comment by ssirois** [comment]
@ventilooo I think you have already published once on npmjs.com therefore, I have assigned you this issue.

**Comment by Manuel-Suarez-Abascal** [comment]
@ssirois @ventilooo @support-savoirfairelinux , I have already added this project to npmjs.com. Here it is the url: https://www.npmjs.com/settings/savoirfairelinux/packages
