### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by edemirkan** [savoirfairelinux/ringme.js#6]
@ssirois Hi there, thank you for the initial code :)
A couple of suggestions if you like;

1. Creating a npm package and publishing it on npmjs.com. This will make it easier for npm users to include ringme.js to their projects. Further more an angular component, again published on npmjs. 
eg: `<ng-ring [action]="call" [identifier]="testusr"></ng-ring>`  This will greatly improve the experience on hybrid app frameworks like Ionic as it's based on Angular 2.
  
2. An improved user agent detection for Android, IOS, Mac OS, Windows e.g;

```
if(navigator.userAgent.indexOf("Android") !== -1) {
     this.isAndroid = true;
     this.ringDownloadLink = "market://details?id=cx.ring"
}
```
to directly send users to appropriate download page instead of generic find-your-own-package style page https://ring.cx/download

**Comment by ssirois** [comment]
Thank you very much for this input.

I shall provide a patch addressing your second suggestion this week.

As for your first suggestion, correct me if I'm wrong but I see two suggestions : 

a. create a npm package out of RingMe.js
b. create an Angular component our of RingMe.js

Both a & b are great suggestions and we shall address them.

To make those suggestions visible, I have created https://github.com/savoirfairelinux/ringme.js/issues/7 and https://github.com/savoirfairelinux/ringme.js/issues/8

**Comment by edemirkan** [comment]
Hey, great to hear from you :)
Further on npmjs deployment, I strongly advise to create a namespace first `@savoirfairelinux`  and publish the packages under it as `@savoirfairelinux/RingMe.js`  and `@savoirfairelinux/angular-RingMe.js` This will create  @savoirfairelinux visibility on npmjs and ease of management for future package deployments. As npmjs delivers the names first come first serve basis this should be done as soon as possible. 

You may also consider creating a separate repo on github (or maybe a branch)  for angular development which I would like to work on :)

**Comment by faraazahmad** [comment]
is the namespace created? i really want to make the angular component. Ring seems cool as they're supporting all major platforms already

**Comment by ssirois** [comment]
@aveferrum thank you for your input. Since this involves an expense (as little as it is), @ventilooo has created an issue (#27) in order to assign this administrative detail to someone (@PipoloyJo) with proper administrative level @savoirfairelinux to make that expense and use the corporation name. This will ease the creation process since eventhough @ventilooo and myself could just pay for the account on npmjs, it would be kinda awkward to use the corporation name without asking first.

**Comment by ssirois** [comment]
@aveferrum feel free to check out https://github.com/savoirfairelinux/angular-ringme.js/issues/1 for the angular component.

Now that both of your suggestions have been addressed, I will close this conversation.

We shall continue in the appropriate locations created and cited above!
