### ISSUE TITLE
Provide a npm package

### ISSUE THREAD

**Issue by ssirois** [savoirfairelinux/ringme.js#7]
As suggested by @demirk4n in https://github.com/savoirfairelinux/ringme.js/issues/6#issue-211897386 :

> A npm package of this project and a publication on npmjs.com would make it easier for npm users to include ringme.js to their projects.

See https://docs.npmjs.com/getting-started/creating-node-modules to get started with this enhancement.

**Comment by ventilooo** [comment]
There it is :
* https://www.npmjs.com/package/ringme.js
_It is temporary under my namespace but it will be later under the organisation **savoirfairelinux**_
